using from './salestypes';
using from './equipmentchapters';
using from './fueltypes';
using from './brandcharacteristics';
using from './modelseries';
using from './drivetypes';
using from './bodytypes';
using from './transmissiontypes';
using from './equipmentcategories';