@authentication = Basic alice:
@basePath = http://localhost:4004
@servicePath = {{basePath}}/pricing-sales-price


POST {{servicePath}}/calculate
Authorization: {{authentication}}
Content-Type: application/json

{
    "table": "AppCarConfiguratorService.Configurations_drafts",
    "ID": "918db7dc-d3aa-4aaf-aa80-f2a3ecc10a23"
}